# Generated by Django 3.2.3 on 2021-05-19 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210519_0346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterModelTable(
            name='account',
            table='account',
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='currency',
            table='currency',
        ),
        migrations.AlterModelTable(
            name='income',
            table='income',
        ),
        migrations.AlterModelTable(
            name='transfer',
            table='transfer',
        ),
    ]
